// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzsWYnc9UFO21mKRChZ1TlZGpyUvT0ZqU',
    appId: '1:343610322886:web:64b59783f91957b4084cc7',
    messagingSenderId: '343610322886',
    projectId: 'textme-85cbd',
    authDomain: 'textme-85cbd.firebaseapp.com',
    storageBucket: 'textme-85cbd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDalS-Noj89sWJAQ6X1vRG8HH3zMaHcIDk',
    appId: '1:343610322886:android:f69ac432661eac02084cc7',
    messagingSenderId: '343610322886',
    projectId: 'textme-85cbd',
    storageBucket: 'textme-85cbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7f1wZC1HUxCNlRx4MA9vmqjCpaT77OwY',
    appId: '1:343610322886:ios:109a3048011017ae084cc7',
    messagingSenderId: '343610322886',
    projectId: 'textme-85cbd',
    storageBucket: 'textme-85cbd.appspot.com',
    iosClientId: '343610322886-9fkkr6ti5srm3bgbaffp3lg5lk37gu4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7f1wZC1HUxCNlRx4MA9vmqjCpaT77OwY',
    appId: '1:343610322886:ios:109a3048011017ae084cc7',
    messagingSenderId: '343610322886',
    projectId: 'textme-85cbd',
    storageBucket: 'textme-85cbd.appspot.com',
    iosClientId: '343610322886-9fkkr6ti5srm3bgbaffp3lg5lk37gu4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
